# Generated by Django 5.0.6 on 2024-08-25 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_colorblindimage_subtype_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='colorblindimage',
            name='user',
        ),
    ]
