# Generated by Django 5.0.6 on 2024-06-21 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_last_login_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorblindImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='colorblind_images/')),
                ('type', models.CharField(choices=[('protanomalous', 'Protanomalous'), ('deuteranomalous', 'Deuteranomalous'), ('tritanomalous', 'Tritanomalous')], max_length=50)),
                ('subtype', models.CharField(blank=True, max_length=50, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
