# Generated by Django 5.0.6 on 2024-06-22 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_colorblindimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorblindimage',
            name='subtype',
            field=models.CharField(blank=True, choices=[('protanomalous', 'Protanomalous'), ('deuteranomalous', 'Deuteranomalous'), ('tritanomalous', 'Tritanomalous'), ('protanopia', 'Protanopia'), ('deuteranopia', 'Deuteranopia'), ('tritanopia', 'Tritanopia')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='colorblindimage',
            name='type',
            field=models.CharField(choices=[('anomalous_trichromatic', 'Tricromático Anómalo'), ('dichromatic', 'Dicromático'), ('achromatic', 'Acromático')], max_length=50),
        ),
    ]
